// line 1 "src/main/ragel/CssParser.rl"
/*
 * Copyright (c) 2008, Piccolo2D project, http://piccolo2d.org
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification, are permitted provided
 * that the following conditions are met:
 *
 * Redistributions of source code must retain the above copyright notice, this list of conditions
 * and the following disclaimer.
 *
 * Redistributions in binary form must reproduce the above copyright notice, this list of conditions
 * and the following disclaimer in the documentation and/or other materials provided with the
 * distribution.
 *
 * None of the name of the Piccolo2D project, the University of Maryland, or the names of its contributors
 * may be used to endorse or promote products derived from this software without specific prior written
 * permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
 * PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
 * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package org.piccolo2d.svg.css;

import java.util.LinkedHashMap;
import java.text.ParseException;

/** <a href="http://research.cs.queensu.ca/~thurston/ragel/">Ragel> parser 
 * for <a href="http://www.w3.org/TR/CSS21/grammar.html">CSS</a> - This file is auto-generated by rl2java.sh.
 * <p>
 * DO NOT EDIT MANUALLY!!!
 * </p>
 * See Also:<ul>
 * <li>Another CSS Grammar: http://www.w3.org/TR/CSS21/syndata.html</li>
 * <li>A ragel css grammar: http://labs.ohloh.net/ohcount/browser/ext/ohcount_native/ragel_parsers/css.rl?rev=83e15c94ca8c53994ef07cdb6c7a5ceffe67884c</li>
 * </ul>
 */
class CssParser extends CssParserBase {
// line 132 "src/main/ragel/CssParser.rl"



// line 50 "src/main/java/org/piccolo2d/svg/css/CssParser.java"
private static byte[] init__css_actions_0()
{
	return new byte [] {
	    0,    1,    0,    1,    1,    1,    2,    1,    4,    1,    7,    1,
	    8,    1,    9,    2,    0,    1,    2,    2,    0,    2,    3,    0,
	    2,    4,    0,    2,    5,    6,    3,    2,    5,    6,    3,    4,
	    5,    6,    3,    9,    0,    1,    3,    9,    3,    0
	};
}

private static final byte _css_actions[] = init__css_actions_0();


private static byte[] init__css_key_offsets_0()
{
	return new byte [] {
	    0,    0,    6,   12,   22,   27,   41,   51,   63,   67,   72,   77,
	   82,   96,  106
	};
}

private static final byte _css_key_offsets[] = init__css_key_offsets_0();


private static char[] init__css_trans_keys_0()
{
	return new char [] {
	   32,   44,   46,  123,    9,   13,   32,   44,   46,  123,    9,   13,
	   32,   42,   46,   95,    9,   13,   65,   90,   97,  122,   95,   65,
	   90,   97,  122,   32,   44,   45,   46,   95,  123,    9,   13,   48,
	   57,   65,   90,   97,  122,   32,   59,   95,  125,    9,   13,   65,
	   90,   97,  122,   32,   45,   58,   95,    9,   13,   48,   57,   65,
	   90,   97,  122,   32,   58,    9,   13,   32,   59,  125,    9,   13,
	   32,   59,  125,    9,   13,   32,   59,  125,    9,   13,   32,   44,
	   45,   46,   95,  123,    9,   13,   48,   57,   65,   90,   97,  122,
	   32,   42,   46,   95,    9,   13,   65,   90,   97,  122,   32,   42,
	   46,   95,    9,   13,   65,   90,   97,  122,    0
	};
}

private static final char _css_trans_keys[] = init__css_trans_keys_0();


private static byte[] init__css_single_lengths_0()
{
	return new byte [] {
	    0,    4,    4,    4,    1,    6,    4,    4,    2,    3,    3,    3,
	    6,    4,    4
	};
}

private static final byte _css_single_lengths[] = init__css_single_lengths_0();


private static byte[] init__css_range_lengths_0()
{
	return new byte [] {
	    0,    1,    1,    3,    2,    4,    3,    4,    1,    1,    1,    1,
	    4,    3,    3
	};
}

private static final byte _css_range_lengths[] = init__css_range_lengths_0();


private static byte[] init__css_index_offsets_0()
{
	return new byte [] {
	    0,    0,    6,   12,   20,   24,   35,   43,   52,   56,   61,   66,
	   71,   82,   90
	};
}

private static final byte _css_index_offsets[] = init__css_index_offsets_0();


private static byte[] init__css_indicies_0()
{
	return new byte [] {
	    0,    2,    3,    4,    0,    1,    5,    6,    7,    8,    5,    1,
	    9,   10,   11,   12,    9,   12,   12,    1,   13,   13,   13,    1,
	   14,   15,   13,   16,   13,   17,   14,   13,   13,   13,    1,   18,
	   18,   19,   20,   18,   19,   19,    1,   21,   22,   23,   22,   21,
	   22,   22,   22,    1,   24,   25,   24,    1,   25,    1,    1,   25,
	   26,   28,   29,   30,   28,   27,   31,   18,   20,   31,    1,    0,
	    2,   32,    3,   32,    4,    0,   32,   32,   32,    1,   33,   10,
	   11,   12,   33,   12,   12,    1,   20,   34,   35,   36,   20,   36,
	   36,    1,    0
	};
}

private static final byte _css_indicies[] = init__css_indicies_0();


private static byte[] init__css_trans_targs_0()
{
	return new byte [] {
	    2,    0,    3,    4,    6,    2,    3,    4,    6,    3,    1,    4,
	   12,    5,    2,    3,    4,    6,    6,    7,   14,    8,    7,    9,
	    8,    9,   10,   10,   11,    6,   14,   11,   12,   13,    1,    4,
	   12
	};
}

private static final byte _css_trans_targs[] = init__css_trans_targs_0();


private static byte[] init__css_trans_actions_0()
{
	return new byte [] {
	    5,    0,   30,   18,   30,    0,   27,    1,   27,    0,   15,   21,
	   15,    3,    7,   34,   24,   34,    0,   15,    0,    9,    3,    9,
	    0,    0,   15,    3,   11,   11,   11,    0,    3,    0,   38,   42,
	   38
	};
}

private static final byte _css_trans_actions[] = init__css_trans_actions_0();


private static byte[] init__css_eof_actions_0()
{
	return new byte [] {
	    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
	    0,    0,   13
	};
}

private static final byte _css_eof_actions[] = init__css_eof_actions_0();


static final int css_start = 13;
static final int css_first_final = 13;
static final int css_error = 0;

static final int css_en_main = 13;

// line 135 "src/main/ragel/CssParser.rl"

	final LinkedHashMap parse(final CharSequence data, final LinkedHashMap css) throws ParseException {
		return parse(data.toString().toCharArray(), css);
	}

	// LinkedHashMap<Pattern, Map<CharSequence, CharSequence>>
	final LinkedHashMap parse(final char[] data, LinkedHashMap css) throws ParseException {
		if(css == null)
			css = new LinkedHashMap();
		// high-level buffers
		final StringBuilder buf = new StringBuilder();
		final double[] argv = new double[7];
		int argc = 0;
		boolean absolute = true;
		
		// ragel variables (low level)
		final int pe = data.length;
		final int eof = pe;
		int cs, p = 0;
		int top;

		
// line 211 "src/main/java/org/piccolo2d/svg/css/CssParser.java"
	{
	cs = css_start;
	}
// line 157 "src/main/ragel/CssParser.rl"
		
// line 217 "src/main/java/org/piccolo2d/svg/css/CssParser.java"
	{
	int _klen;
	int _trans = 0;
	int _acts;
	int _nacts;
	int _keys;
	int _goto_targ = 0;

	_goto: while (true) {
	switch ( _goto_targ ) {
	case 0:
	if ( p == pe ) {
		_goto_targ = 4;
		continue _goto;
	}
	if ( cs == 0 ) {
		_goto_targ = 5;
		continue _goto;
	}
case 1:
	_match: do {
	_keys = _css_key_offsets[cs];
	_trans = _css_index_offsets[cs];
	_klen = _css_single_lengths[cs];
	if ( _klen > 0 ) {
		int _lower = _keys;
		int _mid;
		int _upper = _keys + _klen - 1;
		while (true) {
			if ( _upper < _lower )
				break;

			_mid = _lower + ((_upper-_lower) >> 1);
			if ( data[p] < _css_trans_keys[_mid] )
				_upper = _mid - 1;
			else if ( data[p] > _css_trans_keys[_mid] )
				_lower = _mid + 1;
			else {
				_trans += (_mid - _keys);
				break _match;
			}
		}
		_keys += _klen;
		_trans += _klen;
	}

	_klen = _css_range_lengths[cs];
	if ( _klen > 0 ) {
		int _lower = _keys;
		int _mid;
		int _upper = _keys + (_klen<<1) - 2;
		while (true) {
			if ( _upper < _lower )
				break;

			_mid = _lower + (((_upper-_lower) >> 1) & ~1);
			if ( data[p] < _css_trans_keys[_mid] )
				_upper = _mid - 2;
			else if ( data[p] > _css_trans_keys[_mid+1] )
				_lower = _mid + 2;
			else {
				_trans += ((_mid - _keys)>>1);
				break _match;
			}
		}
		_trans += _klen;
	}
	} while (false);

	_trans = _css_indicies[_trans];
	cs = _css_trans_targs[_trans];

	if ( _css_trans_actions[_trans] != 0 ) {
		_acts = _css_trans_actions[_trans];
		_nacts = (int) _css_actions[_acts++];
		while ( _nacts-- > 0 )
	{
			switch ( _css_actions[_acts++] )
			{
	case 0:
// line 52 "src/main/ragel/CssParser.rl"
	{
		buf.setLength(0);
	}
	break;
	case 1:
// line 56 "src/main/ragel/CssParser.rl"
	{
		buf.append(data[p]);
	}
	break;
	case 2:
// line 60 "src/main/ragel/CssParser.rl"
	{
		pushElement(buf);
	}
	break;
	case 3:
// line 64 "src/main/ragel/CssParser.rl"
	{
		pushElement(ANY_ELEMENT);
	}
	break;
	case 4:
// line 68 "src/main/ragel/CssParser.rl"
	{
		pushClass(buf);
	}
	break;
	case 5:
// line 72 "src/main/ragel/CssParser.rl"
	{
		finishElement();
	}
	break;
	case 6:
// line 76 "src/main/ragel/CssParser.rl"
	{
		finishSelector();
	}
	break;
	case 7:
// line 80 "src/main/ragel/CssParser.rl"
	{
		pushProperty(buf);
	}
	break;
	case 8:
// line 84 "src/main/ragel/CssParser.rl"
	{
		pushExpr(buf);
	}
	break;
	case 9:
// line 88 "src/main/ragel/CssParser.rl"
	{
		finishRuleSet(css);
	}
	break;
// line 357 "src/main/java/org/piccolo2d/svg/css/CssParser.java"
			}
		}
	}

case 2:
	if ( cs == 0 ) {
		_goto_targ = 5;
		continue _goto;
	}
	if ( ++p != pe ) {
		_goto_targ = 1;
		continue _goto;
	}
case 4:
	if ( p == eof )
	{
	int __acts = _css_eof_actions[cs];
	int __nacts = (int) _css_actions[__acts++];
	while ( __nacts-- > 0 ) {
		switch ( _css_actions[__acts++] ) {
	case 9:
// line 88 "src/main/ragel/CssParser.rl"
	{
		finishRuleSet(css);
	}
	break;
// line 384 "src/main/java/org/piccolo2d/svg/css/CssParser.java"
		}
	}
	}

case 5:
	}
	break; }
	}
// line 158 "src/main/ragel/CssParser.rl"

		if ( cs < css_first_final )
			throw new ParseException(new String(data), p);
        return css;
	}
}
