// line 1 "src/main/ragel/CssParser.rl"
/*
 * Copyright (c) 2008, Piccolo2D project, http://piccolo2d.org
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification, are permitted provided
 * that the following conditions are met:
 *
 * Redistributions of source code must retain the above copyright notice, this list of conditions
 * and the following disclaimer.
 *
 * Redistributions in binary form must reproduce the above copyright notice, this list of conditions
 * and the following disclaimer in the documentation and/or other materials provided with the
 * distribution.
 *
 * None of the name of the Piccolo2D project, the University of Maryland, or the names of its contributors
 * may be used to endorse or promote products derived from this software without specific prior written
 * permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
 * PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
 * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package org.piccolo2d.svg.cssmini;

import java.text.ParseException;
import java.util.Collection;
import java.util.Iterator;
import java.util.LinkedList;

import org.piccolo2d.svg.util.RagelParser;

/** <a href="http://research.cs.queensu.ca/~thurston/ragel/">Ragel</a> parser 
 * for <a href="http://www.w3.org/TR/CSS21/grammar.html">CSS</a> - This file is auto-generated by rl2java.sh.
 * <p>
 * DO NOT EDIT MANUALLY!!!
 * </p>
 * See Also:<ul>
 * <li>Another CSS Grammar: http://www.w3.org/TR/CSS21/syndata.html</li>
 * <li>A ragel css grammar: http://labs.ohloh.net/ohcount/browser/ext/ohcount_native/ragel_parsers/css.rl?rev=83e15c94ca8c53994ef07cdb6c7a5ceffe67884c</li>
 * </ul>
 */
class CssParser implements RagelParser {
// line 165 "src/main/ragel/CssParser.rl"



// line 54 "src/main/java/org/piccolo2d/svg/cssmini/CssParser.java"
private static byte[] init__css_actions_0()
{
	return new byte [] {
	    0,    1,    0,    1,    1,    1,    2,    1,    4,    1,    5,    1,
	    9,    1,   10,    1,   11,    1,   12,    1,   14,    2,    3,    6,
	    2,    3,    8,    2,    7,    0,    2,    7,    2,    2,   13,    0,
	    2,   13,    2,    2,   13,   14,    3,    1,    3,    6,    3,    1,
	    3,    8,    3,    3,    7,    0,    3,    3,    7,    2,    3,    5,
	    3,    6,    3,    5,    3,    8,    4,    1,    3,    7,    2,    4,
	    5,    3,    7,    2
	};
}

private static final byte _css_actions[] = init__css_actions_0();


private static byte[] init__css_key_offsets_0()
{
	return new byte [] {
	    0,    0,   14,   24,   29,   46,   56,   73,   83,   95,   99,  104,
	  109,  114,  124
	};
}

private static final byte _css_key_offsets[] = init__css_key_offsets_0();


private static char[] init__css_trans_keys_0()
{
	return new char [] {
	   32,   42,   43,   44,   46,   62,   95,  123,    9,   13,   65,   90,
	   97,  122,   32,   42,   46,   95,    9,   13,   65,   90,   97,  122,
	   95,   65,   90,   97,  122,   32,   42,   43,   44,   45,   46,   62,
	   95,  123,    9,   13,   48,   57,   65,   90,   97,  122,   32,   42,
	   46,   95,    9,   13,   65,   90,   97,  122,   32,   42,   43,   44,
	   45,   46,   62,   95,  123,    9,   13,   48,   57,   65,   90,   97,
	  122,   32,   59,   95,  125,    9,   13,   65,   90,   97,  122,   32,
	   45,   58,   95,    9,   13,   48,   57,   65,   90,   97,  122,   32,
	   58,    9,   13,   32,   59,  125,    9,   13,   32,   59,  125,    9,
	   13,   32,   59,  125,    9,   13,   32,   42,   46,   95,    9,   13,
	   65,   90,   97,  122,   32,   42,   46,   95,    9,   13,   65,   90,
	   97,  122,    0
	};
}

private static final char _css_trans_keys[] = init__css_trans_keys_0();


private static byte[] init__css_single_lengths_0()
{
	return new byte [] {
	    0,    8,    4,    1,    9,    4,    9,    4,    4,    2,    3,    3,
	    3,    4,    4
	};
}

private static final byte _css_single_lengths[] = init__css_single_lengths_0();


private static byte[] init__css_range_lengths_0()
{
	return new byte [] {
	    0,    3,    3,    2,    4,    3,    4,    3,    4,    1,    1,    1,
	    1,    3,    3
	};
}

private static final byte _css_range_lengths[] = init__css_range_lengths_0();


private static byte[] init__css_index_offsets_0()
{
	return new byte [] {
	    0,    0,   12,   20,   24,   38,   46,   60,   68,   77,   81,   86,
	   91,   96,  104
	};
}

private static final byte _css_index_offsets[] = init__css_index_offsets_0();


private static byte[] init__css_indicies_0()
{
	return new byte [] {
	    0,    2,    3,    4,    5,    3,    6,    7,    0,    6,    6,    1,
	    8,    9,   10,   11,    8,   11,   11,    1,   12,   12,   12,    1,
	   13,   14,   15,   16,   17,   18,   15,   17,   19,   13,   17,   17,
	   17,    1,   20,   21,   22,   23,   20,   23,   23,    1,   24,   25,
	   26,   27,   28,   29,   26,   28,   30,   24,   28,   28,   28,    1,
	   31,   31,   32,   33,   31,   32,   32,    1,   34,   35,   36,   35,
	   34,   35,   35,   35,    1,   37,   38,   37,    1,   38,    1,    1,
	   38,   39,   41,   42,   43,   41,   40,   44,   31,   33,   44,    1,
	   45,   21,   22,   23,   45,   23,   23,    1,   33,   46,   47,   48,
	   33,   48,   48,    1,    0
	};
}

private static final byte _css_indicies[] = init__css_indicies_0();


private static byte[] init__css_trans_targs_0()
{
	return new byte [] {
	    1,    0,    1,    2,    5,    3,    6,    7,    2,    1,    3,    6,
	    4,    1,    1,    2,    5,    4,    3,    7,    5,    1,    3,    6,
	    1,    1,    2,    5,    6,    3,    7,    7,    8,   14,    9,    8,
	   10,    9,   10,   11,   11,   12,    7,   14,   12,   13,    1,    3,
	    6
	};
}

private static final byte _css_trans_targs[] = init__css_trans_targs_0();


private static byte[] init__css_trans_actions_0()
{
	return new byte [] {
	    0,    0,   54,   21,   24,    0,   50,   24,    0,   30,   30,   27,
	    7,    9,   71,   58,   62,    0,    9,   62,    0,    5,    5,    1,
	    3,   66,   42,   46,    0,    3,   46,    0,   11,    0,   13,    0,
	   13,    0,    0,   15,    0,   17,   17,   17,    0,    0,   36,   36,
	   33
	};
}

private static final byte _css_trans_actions[] = init__css_trans_actions_0();


private static byte[] init__css_eof_actions_0()
{
	return new byte [] {
	    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
	    0,   19,   39
	};
}

private static final byte _css_eof_actions[] = init__css_eof_actions_0();


static final int css_start = 13;
static final int css_first_final = 13;
static final int css_error = 0;

static final int css_en_main = 13;

// line 168 "src/main/ragel/CssParser.rl"

    // Collection<CSSStyleRule>
    final Collection parse(final CharSequence data) throws ParseException {
        return parse(data.toString().toCharArray());
    }

    // Collection<CSSStyleRule>
    final Collection parse(final char[] data) throws ParseException {
		// high-level buffers
        final Collection css = new LinkedList();
        if(data == null)
        	return css;
        final Collection sel = new LinkedList();
        final CSSSelector.Builder sB = new CSSSelectorBuilderXPath();
        final CSSStyleDeclaration.Builder dB = new CSSStyleDeclaration.Builder();
        char combinator = ' ';
		int start = -1;
		
		final boolean debug = false;
		
		// ragel variables (low level)
		final int pe = data.length;
		final int eof = pe;
		int cs, p = 0;

		
// line 227 "src/main/java/org/piccolo2d/svg/cssmini/CssParser.java"
	{
	cs = css_start;
	}
// line 194 "src/main/ragel/CssParser.rl"
		
// line 233 "src/main/java/org/piccolo2d/svg/cssmini/CssParser.java"
	{
	int _klen;
	int _trans = 0;
	int _acts;
	int _nacts;
	int _keys;
	int _goto_targ = 0;

	_goto: while (true) {
	switch ( _goto_targ ) {
	case 0:
	if ( p == pe ) {
		_goto_targ = 4;
		continue _goto;
	}
	if ( cs == 0 ) {
		_goto_targ = 5;
		continue _goto;
	}
case 1:
	_match: do {
	_keys = _css_key_offsets[cs];
	_trans = _css_index_offsets[cs];
	_klen = _css_single_lengths[cs];
	if ( _klen > 0 ) {
		int _lower = _keys;
		int _mid;
		int _upper = _keys + _klen - 1;
		while (true) {
			if ( _upper < _lower )
				break;

			_mid = _lower + ((_upper-_lower) >> 1);
			if ( data[p] < _css_trans_keys[_mid] )
				_upper = _mid - 1;
			else if ( data[p] > _css_trans_keys[_mid] )
				_lower = _mid + 1;
			else {
				_trans += (_mid - _keys);
				break _match;
			}
		}
		_keys += _klen;
		_trans += _klen;
	}

	_klen = _css_range_lengths[cs];
	if ( _klen > 0 ) {
		int _lower = _keys;
		int _mid;
		int _upper = _keys + (_klen<<1) - 2;
		while (true) {
			if ( _upper < _lower )
				break;

			_mid = _lower + (((_upper-_lower) >> 1) & ~1);
			if ( data[p] < _css_trans_keys[_mid] )
				_upper = _mid - 2;
			else if ( data[p] > _css_trans_keys[_mid+1] )
				_lower = _mid + 2;
			else {
				_trans += ((_mid - _keys)>>1);
				break _match;
			}
		}
		_trans += _klen;
	}
	} while (false);

	_trans = _css_indicies[_trans];
	cs = _css_trans_targs[_trans];

	if ( _css_trans_actions[_trans] != 0 ) {
		_acts = _css_trans_actions[_trans];
		_nacts = (int) _css_actions[_acts++];
		while ( _nacts-- > 0 )
	{
			switch ( _css_actions[_acts++] )
			{
	case 0:
// line 56 "src/main/ragel/CssParser.rl"
	{
		if(debug) System.out.println("start_element");
		start = p;
	}
	break;
	case 1:
// line 60 "src/main/ragel/CssParser.rl"
	{
		if(debug) System.out.println("push_element [" + new String(data, start, p-start) + "]");
		sB.startElement(new String(data, start, p-start));
		start = -1;
	}
	break;
	case 2:
// line 65 "src/main/ragel/CssParser.rl"
	{
		if(debug) System.out.println("push_wildcard");
		sB.startElement("*");
		start = -1;
	}
	break;
	case 3:
// line 70 "src/main/ragel/CssParser.rl"
	{
		if(debug) System.out.println("end_element " + p);
		sB.endElement();
	}
	break;
	case 4:
// line 75 "src/main/ragel/CssParser.rl"
	{
		if(debug) System.out.println("start_class");
		start = p;
	}
	break;
	case 5:
// line 79 "src/main/ragel/CssParser.rl"
	{
		if(debug) System.out.println("push_class [" + new String(data, start, p-start) + "]");
		sB.addClass(new String(data, start, p-start));
		start = -1;
	}
	break;
	case 6:
// line 85 "src/main/ragel/CssParser.rl"
	{
		if(debug) System.out.println("push_combinator [" + data[p] + "]");
		combinator = data[p];
	}
	break;
	case 7:
// line 89 "src/main/ragel/CssParser.rl"
	{
		if(debug) System.out.println("combined");
		sB.combinator(combinator);
		combinator = ' ';
	}
	break;
	case 8:
// line 95 "src/main/ragel/CssParser.rl"
	{
		if(debug) System.out.println("end_selector [" + p + "] ");
		sel.add(sB.finish());
	}
	break;
	case 9:
// line 100 "src/main/ragel/CssParser.rl"
	{
		if(debug) System.out.println("start_prop_key");
		start = p;
	}
	break;
	case 10:
// line 104 "src/main/ragel/CssParser.rl"
	{
		if(debug) System.out.println("push_prop_key [" + new String(data, start, p-start) + "]");
		dB.addKey(new String(data, start, p-start));
		start = -1;
	}
	break;
	case 11:
// line 110 "src/main/ragel/CssParser.rl"
	{
		if(debug) System.out.println("start_prop_value");
		start = p;
	}
	break;
	case 12:
// line 114 "src/main/ragel/CssParser.rl"
	{
		if(debug) System.out.println("push_prop_value [" + new String(data, start, p-start) + "]");
		dB.addValue(new String(data, start, p-start));
		start = -1;
	}
	break;
	case 13:
// line 120 "src/main/ragel/CssParser.rl"
	{
		if(debug) System.out.println("end_definition");
		final CSSStyleDeclaration s = dB.finish();
		for(Iterator it = sel.iterator(); it.hasNext();) {
			css.add(new CSSStyleRule((CSSSelector) it.next(), s));
		}
		sel.clear();
	}
	break;
// line 421 "src/main/java/org/piccolo2d/svg/cssmini/CssParser.java"
			}
		}
	}

case 2:
	if ( cs == 0 ) {
		_goto_targ = 5;
		continue _goto;
	}
	if ( ++p != pe ) {
		_goto_targ = 1;
		continue _goto;
	}
case 4:
	if ( p == eof )
	{
	int __acts = _css_eof_actions[cs];
	int __nacts = (int) _css_actions[__acts++];
	while ( __nacts-- > 0 ) {
		switch ( _css_actions[__acts++] ) {
	case 13:
// line 120 "src/main/ragel/CssParser.rl"
	{
		if(debug) System.out.println("end_definition");
		final CSSStyleDeclaration s = dB.finish();
		for(Iterator it = sel.iterator(); it.hasNext();) {
			css.add(new CSSStyleRule((CSSSelector) it.next(), s));
		}
		sel.clear();
	}
	break;
	case 14:
// line 164 "src/main/ragel/CssParser.rl"
	{if(debug) System.out.println("---");}
	break;
// line 457 "src/main/java/org/piccolo2d/svg/cssmini/CssParser.java"
		}
	}
	}

case 5:
	}
	break; }
	}
// line 195 "src/main/ragel/CssParser.rl"

		if ( cs < css_first_final )
			throw new ParseException(new String(data), p);
        return css;
	}
}
