
// line 1 "src/main/ragel/CssSelectorToXPath.rl"
/*
 * Copyright (c) 2008, Piccolo2D project, http://piccolo2d.org
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification, are permitted provided
 * that the following conditions are met:
 *
 * Redistributions of source code must retain the above copyright notice, this list of conditions
 * and the following disclaimer.
 *
 * Redistributions in binary form must reproduce the above copyright notice, this list of conditions
 * and the following disclaimer in the documentation and/or other materials provided with the
 * distribution.
 *
 * None of the name of the Piccolo2D project, the University of Maryland, or the names of its contributors
 * may be used to endorse or promote products derived from this software without specific prior written
 * permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
 * PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
 * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package org.piccolo2d.svg.cssmini;

import java.text.ParseException;
import java.util.Collections;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;

import org.piccolo2d.svg.util.RagelParser;

/** <a href="http://research.cs.queensu.ca/~thurston/ragel/">Ragel</a> parser 
 * for <a href="http://www.w3.org/TR/CSS21/grammar.html">CSS</a> - This file is auto-generated by rl2java.sh.
 * <p>
 * DO NOT EDIT MANUALLY!!!
 * </p>
 * See Also:<ul>
 * <li>Another CSS Grammar: http://www.w3.org/TR/CSS21/syndata.html</li>
 * <li>A ragel css grammar: http://labs.ohloh.net/ohcount/browser/ext/ohcount_native/ragel_parsers/css.rl?rev=83e15c94ca8c53994ef07cdb6c7a5ceffe67884c</li>
 * </ul>
 */
class CssSelectorToXPath implements RagelParser {

// line 132 "src/main/ragel/CssSelectorToXPath.rl"



// line 57 "src/main/java/org/piccolo2d/svg/cssmini/CssSelectorToXPath.java"
private static byte[] init__selector_actions_0()
{
	return new byte [] {
	    0,    1,    0,    1,    1,    1,    2,    1,    4,    1,    5,    2,
	    3,    6,    2,    7,    0,    2,    7,    2,    3,    1,    3,    6,
	    3,    3,    7,    0,    3,    3,    7,    2,    3,    3,    8,    9,
	    3,    5,    3,    6,    4,    1,    3,    7,    2,    4,    1,    3,
	    8,    9,    4,    5,    3,    7,    2,    4,    5,    3,    8,    9
	};
}

private static final byte _selector_actions[] = init__selector_actions_0();


private static byte[] init__selector_key_offsets_0()
{
	return new byte [] {
	    0,    0,   10,   20,   25,   37,   52
	};
}

private static final byte _selector_key_offsets[] = init__selector_key_offsets_0();


private static char[] init__selector_trans_keys_0()
{
	return new char [] {
	   32,   42,   46,   95,    9,   13,   65,   90,   97,  122,   32,   42,
	   46,   95,    9,   13,   65,   90,   97,  122,   95,   65,   90,   97,
	  122,   32,   42,   43,   46,   62,   95,    9,   13,   65,   90,   97,
	  122,   32,   42,   43,   45,   46,   62,   95,    9,   13,   48,   57,
	   65,   90,   97,  122,   32,   42,   43,   45,   46,   62,   95,    9,
	   13,   48,   57,   65,   90,   97,  122,    0
	};
}

private static final char _selector_trans_keys[] = init__selector_trans_keys_0();


private static byte[] init__selector_single_lengths_0()
{
	return new byte [] {
	    0,    4,    4,    1,    6,    7,    7
	};
}

private static final byte _selector_single_lengths[] = init__selector_single_lengths_0();


private static byte[] init__selector_range_lengths_0()
{
	return new byte [] {
	    0,    3,    3,    2,    3,    4,    4
	};
}

private static final byte _selector_range_lengths[] = init__selector_range_lengths_0();


private static byte[] init__selector_index_offsets_0()
{
	return new byte [] {
	    0,    0,    8,   16,   20,   30,   42
	};
}

private static final byte _selector_index_offsets[] = init__selector_index_offsets_0();


private static byte[] init__selector_indicies_0()
{
	return new byte [] {
	    0,    2,    3,    4,    0,    4,    4,    1,    5,    6,    7,    8,
	    5,    8,    8,    1,    9,    9,    9,    1,   10,   11,   12,   13,
	   12,   14,   10,   14,   14,    1,   15,   16,   17,   18,   19,   17,
	   18,   15,   18,   18,   18,    1,   20,   21,   22,   23,   24,   22,
	   23,   20,   23,   23,   23,    1,    0
	};
}

private static final byte _selector_indicies[] = init__selector_indicies_0();


private static byte[] init__selector_trans_targs_0()
{
	return new byte [] {
	    1,    0,    4,    3,    6,    2,    4,    3,    6,    5,    4,    4,
	    2,    3,    6,    4,    4,    2,    5,    3,    4,    4,    2,    6,
	    3
	};
}

private static final byte _selector_trans_targs[] = init__selector_trans_targs_0();


private static byte[] init__selector_trans_actions_0()
{
	return new byte [] {
	    0,    0,    5,    5,    1,    0,   17,   17,   14,    7,    0,   28,
	   11,    0,   24,    9,   50,   36,    0,    9,    3,   40,   20,    0,
	    3
	};
}

private static final byte _selector_trans_actions[] = init__selector_trans_actions_0();


private static byte[] init__selector_eof_actions_0()
{
	return new byte [] {
	    0,    0,    0,    0,   32,   55,   45
	};
}

private static final byte _selector_eof_actions[] = init__selector_eof_actions_0();


static final int selector_start = 1;
static final int selector_first_final = 4;
static final int selector_error = 0;

static final int selector_en_main = 1;


// line 135 "src/main/ragel/CssSelectorToXPath.rl"

    final CharSequence parse(final CharSequence data) throws ParseException {
        return parse(data.toString().toCharArray());
    }

    final CharSequence parse(final char[] data) throws ParseException {
		// high-level buffers
        final List classes = new LinkedList();
        final StringBuffer xpath = new StringBuffer();
        char combinator = ' ';
		int start = -1;
		
		final boolean debug = false;
		
		// ragel variables (low level)
		final int pe = data.length;
		final int eof = pe;
		int cs, p = 0;

		
// line 203 "src/main/java/org/piccolo2d/svg/cssmini/CssSelectorToXPath.java"
	{
	cs = selector_start;
	}

// line 155 "src/main/ragel/CssSelectorToXPath.rl"
		
// line 210 "src/main/java/org/piccolo2d/svg/cssmini/CssSelectorToXPath.java"
	{
	int _klen;
	int _trans = 0;
	int _acts;
	int _nacts;
	int _keys;
	int _goto_targ = 0;

	_goto: while (true) {
	switch ( _goto_targ ) {
	case 0:
	if ( p == pe ) {
		_goto_targ = 4;
		continue _goto;
	}
	if ( cs == 0 ) {
		_goto_targ = 5;
		continue _goto;
	}
case 1:
	_match: do {
	_keys = _selector_key_offsets[cs];
	_trans = _selector_index_offsets[cs];
	_klen = _selector_single_lengths[cs];
	if ( _klen > 0 ) {
		int _lower = _keys;
		int _mid;
		int _upper = _keys + _klen - 1;
		while (true) {
			if ( _upper < _lower )
				break;

			_mid = _lower + ((_upper-_lower) >> 1);
			if ( data[p] < _selector_trans_keys[_mid] )
				_upper = _mid - 1;
			else if ( data[p] > _selector_trans_keys[_mid] )
				_lower = _mid + 1;
			else {
				_trans += (_mid - _keys);
				break _match;
			}
		}
		_keys += _klen;
		_trans += _klen;
	}

	_klen = _selector_range_lengths[cs];
	if ( _klen > 0 ) {
		int _lower = _keys;
		int _mid;
		int _upper = _keys + (_klen<<1) - 2;
		while (true) {
			if ( _upper < _lower )
				break;

			_mid = _lower + (((_upper-_lower) >> 1) & ~1);
			if ( data[p] < _selector_trans_keys[_mid] )
				_upper = _mid - 2;
			else if ( data[p] > _selector_trans_keys[_mid+1] )
				_lower = _mid + 2;
			else {
				_trans += ((_mid - _keys)>>1);
				break _match;
			}
		}
		_trans += _klen;
	}
	} while (false);

	_trans = _selector_indicies[_trans];
	cs = _selector_trans_targs[_trans];

	if ( _selector_trans_actions[_trans] != 0 ) {
		_acts = _selector_trans_actions[_trans];
		_nacts = (int) _selector_actions[_acts++];
		while ( _nacts-- > 0 )
	{
			switch ( _selector_actions[_acts++] )
			{
	case 0:
// line 57 "src/main/ragel/CssSelectorToXPath.rl"
	{
		if(debug) System.out.println("start_element");
		start = p;
	}
	break;
	case 1:
// line 61 "src/main/ragel/CssSelectorToXPath.rl"
	{
		if(debug) System.out.println("push_element [" + new String(data, start, p-start) + "]");
		xpath.append('/').append(data, start, p-start);
		start = -1;
	}
	break;
	case 2:
// line 66 "src/main/ragel/CssSelectorToXPath.rl"
	{
		if(debug) System.out.println("push_wildcard");
		xpath.append("/*");
		start = -1;
	}
	break;
	case 3:
// line 71 "src/main/ragel/CssSelectorToXPath.rl"
	{
		if(debug) System.out.println("end_element " + p);
		if(classes.size() > 0) {
			Collections.sort(classes);
			xpath.append("[@class='");
			Iterator it = classes.iterator();
			xpath.append(it.next());
			while(it.hasNext()) {
				xpath.append(' ').append(it.next());
			}
			xpath.append("']");
			classes.clear();
		}		
	}
	break;
	case 4:
// line 86 "src/main/ragel/CssSelectorToXPath.rl"
	{
		if(debug) System.out.println("start_class");
		start = p;
	}
	break;
	case 5:
// line 90 "src/main/ragel/CssSelectorToXPath.rl"
	{
		if(debug) System.out.println("push_class [" + new String(data, start, p-start) + "]");
		classes.add(new String(data, start, p-start));
		start = -1;
	}
	break;
	case 6:
// line 96 "src/main/ragel/CssSelectorToXPath.rl"
	{
		if(debug) System.out.println("push_combinator [" + data[p] + "]");
		combinator = data[p];
	}
	break;
	case 7:
// line 100 "src/main/ragel/CssSelectorToXPath.rl"
	{
		if(debug) System.out.println("combined");
		switch(combinator) {
		case ' ': xpath.append('/'); break;
		case '>': break;
		default: throw new UnsupportedOperationException("Combinator [" + data[p] + "] not supported.");
		};
		combinator = ' ';
	}
	break;
// line 364 "src/main/java/org/piccolo2d/svg/cssmini/CssSelectorToXPath.java"
			}
		}
	}

case 2:
	if ( cs == 0 ) {
		_goto_targ = 5;
		continue _goto;
	}
	if ( ++p != pe ) {
		_goto_targ = 1;
		continue _goto;
	}
case 4:
	if ( p == eof )
	{
	int __acts = _selector_eof_actions[cs];
	int __nacts = (int) _selector_actions[__acts++];
	while ( __nacts-- > 0 ) {
		switch ( _selector_actions[__acts++] ) {
	case 1:
// line 61 "src/main/ragel/CssSelectorToXPath.rl"
	{
		if(debug) System.out.println("push_element [" + new String(data, start, p-start) + "]");
		xpath.append('/').append(data, start, p-start);
		start = -1;
	}
	break;
	case 3:
// line 71 "src/main/ragel/CssSelectorToXPath.rl"
	{
		if(debug) System.out.println("end_element " + p);
		if(classes.size() > 0) {
			Collections.sort(classes);
			xpath.append("[@class='");
			Iterator it = classes.iterator();
			xpath.append(it.next());
			while(it.hasNext()) {
				xpath.append(' ').append(it.next());
			}
			xpath.append("']");
			classes.clear();
		}		
	}
	break;
	case 5:
// line 90 "src/main/ragel/CssSelectorToXPath.rl"
	{
		if(debug) System.out.println("push_class [" + new String(data, start, p-start) + "]");
		classes.add(new String(data, start, p-start));
		start = -1;
	}
	break;
	case 8:
// line 110 "src/main/ragel/CssSelectorToXPath.rl"
	{
		if(debug) System.out.println("end_selector [" + p + "] ");
	}
	break;
	case 9:
// line 131 "src/main/ragel/CssSelectorToXPath.rl"
	{if(debug) System.out.println("---");}
	break;
// line 428 "src/main/java/org/piccolo2d/svg/cssmini/CssSelectorToXPath.java"
		}
	}
	}

case 5:
	}
	break; }
	}

// line 156 "src/main/ragel/CssSelectorToXPath.rl"

		if (cs < selector_first_final)
			throw new ParseException(new String(data), p);
        return xpath.toString();
	}
}
